#packages utilisés ---
library(readxl)
library(dplyr)
library(stringr)
library(sf)
library(shiny)
library(bslib)
library(ggplot2)
library(tidyverse)
library(GGally)
library(corrplot)
library(RColorBrewer)
library(ggthemes)
library(factoextra)
library(patchwork)
library(scales)
library(forcats)

dtaf_loaded <- readRDS("data/dtaf.RDS")
