
dtaf_loaded_dt<- dtaf_loaded %>% # création d'un df  pour l'affichage de la table 
st_drop_geometry() %>% # on retire la geometry (carte)
  rename( # on renomme l'ensemble des variables pour donner des noms clairs
    "Code du département" = codeDepartement,
    "Nom du département" = nomDepartement,
    "Code de la circonscription" = codeCirconscription,
    "Nom de la circonscription" = nomCirconscription,
    "Inscrits 2022" = Inscrit_22,
    "Population légale 2019" = pop_légal_19,
    "% pop. pôles AAV" = pop_pole_aav,
    "% pop. couronnes AAV" = pop_cour_aav,
    "% pop. hors AAV" = pop_horsaav,
    "% pop. urbaine" = pop_urb,
    "% pop. rurale périurbaine" = pop_rur_periu,
    "% pop. rurale non périurbaine" = pop_rur_non_periu,
    "Âge moyen" = age_moyen,
    "% actifs en emploi" = actemp,
    "% chômeurs" = actcho,
    "% inactifs retraités" = inactret,
    "Sans diplôme" = actdip_PEU,
    "CAP-BEP" = actdip_CAP,
    "BAC" = actdip_BAC,
    "Bac+2" = actdip_BAC2,
    "Bac+3" = actdip_BAC3,
    "Bac+5" = actdip_BAC5,
    "Bac+3+" = actdip_BAC3P,
    "% agriculteurs" = act_agr,
    "% artisans/com." = act_art,
    "% cadres" = act_cad,
    "% prof. intermédiaires" = act_int,
    "% employés" = act_emp,
    "% ouvriers" = act_ouv,
    "% chômage" = act_cho,
    "% ménages seuls" = men_seul,
    "% couples avec enfants" = men_coupae,
    "% couples sans enfants" = men_coupse,
    "% familles monoparentales" = men_monop,
    "% propriétaires" = proprio,
    "% locataires" = locatai,
    "% chauffage fioul" = mfuel,
    "% aucun transport" = modtrans_aucun,
    "% à pied" = modtrans_pied,
    "% vélo" = modtrans_velo,
    "% moto" = modtrans_moto,
    "% voiture" = modtrans_voit,
    "% transports en commun" = modtrans_commun,
    "% accès école" = acc_ecole,
    "% accès collège" = acc_college,
    "% accès lycée" = acc_lycee,
    "% accès médecin" = acc_medecin,
    "% accès dentiste" = acc_dentiste,
    "% accès pharmacie" = acc_pharmacie,
    "Taux de pauvreté (60%)" = tx_pauvrete60_diff,
    "Niveau de vie médian" = nivvie_median_diff,
    "Vote majoritaire" = Gagnant,
    "Taux d'abstension" = Abs_insc,
    "Taux de vote" = Vot_insc,
    "% Votes blans" = Blanc_vote,
    "% Votes nuls" = Nul_vote,
    "Votes exprimés pour Arthaud" = Arthaud_exp,
    "Votes exprimés pour Roussel" = Roussel_exp,
    "Votes exprimés pour Macron" = Macron_exp,
    "Votes exprimés pour Lasalle" = Lassalle_exp,
    "Votes exprimés pour Le Pen" = LePen_exp,
    "Votes exprimés pour Zemmour" = Zemmour_exp,
    "Votes exprimés pour Mélenchon" = Melenchon_exp,
    "Votes exprimés pour Hidalgo" = Hidalgo_exp,
    "Votes exprimés pour Jadot" = Jadot_exp,
    "Votes exprimés pour Pécresse" = Pecresse_exp,
    "Votes exprimés pour Poutou" = Poutou_exp,
    "Votes exprimés pour Dupont-Aignan" = DupontAignan_exp)

  # création de l'output de la table
  output$table <- renderDT({
    DT::datatable(dtaf_loaded_dt,
                  options = list(pageLength = 10)) # affichage 10 lignes par défaut
  })